// Code generated by goyacc -o ./sqlparser/sql.go ./sqlparser/sql.y. DO NOT EDIT.

//line ./sqlparser/sql.y:20
package sqlparser

import __yyfmt__ "fmt"

//line ./sqlparser/sql.y:20

import "bytes"

func SetParseTree(yylex interface{}, stmt Statement) {
	yylex.(*Tokenizer).ParseTree = stmt
}

func SetAllowComments(yylex interface{}, allow bool) {
	yylex.(*Tokenizer).AllowComments = allow
}

func ForceEOF(yylex interface{}) {
	yylex.(*Tokenizer).ForceEOF = true
}

var (
	SHARE        = []byte("share")
	MODE         = []byte("mode")
	IF_BYTES     = []byte("if")
	VALUES_BYTES = []byte("values")
)

//line ./sqlparser/sql.y:45
type yySymType struct {
	yys         int
	empty       struct{}
	statement   Statement
	selStmt     SelectStatement
	byt         byte
	bytes       []byte
	bytes2      [][]byte
	str         string
	selectExprs SelectExprs
	selectExpr  SelectExpr
	columns     Columns
	colName     *ColName
	tableExprs  TableExprs
	tableExpr   TableExpr
	smTableExpr SimpleTableExpr
	tableName   *TableName
	indexHints  *IndexHints
	expr        Expr
	boolExpr    BoolExpr
	valExpr     ValExpr
	tuple       Tuple
	valExprs    ValExprs
	values      Values
	subquery    *Subquery
	caseExpr    *CaseExpr
	whens       []*When
	when        *When
	orderBy     OrderBy
	order       *Order
	limit       *Limit
	insRows     InsertRows
	updateExprs UpdateExprs
	updateExpr  *UpdateExpr
}

const LEX_ERROR = 57346
const SELECT = 57347
const INSERT = 57348
const UPDATE = 57349
const DELETE = 57350
const FROM = 57351
const WHERE = 57352
const GROUP = 57353
const HAVING = 57354
const ORDER = 57355
const BY = 57356
const LIMIT = 57357
const FOR = 57358
const ALL = 57359
const DISTINCT = 57360
const AS = 57361
const EXISTS = 57362
const NULL = 57363
const ASC = 57364
const DESC = 57365
const VALUES = 57366
const INTO = 57367
const DUPLICATE = 57368
const KEY = 57369
const DEFAULT = 57370
const SET = 57371
const LOCK = 57372
const ID = 57373
const STRING = 57374
const NUMBER = 57375
const VALUE_ARG = 57376
const COMMENT = 57377
const UNION = 57378
const MINUS = 57379
const EXCEPT = 57380
const INTERSECT = 57381
const JOIN = 57382
const STRAIGHT_JOIN = 57383
const LEFT = 57384
const RIGHT = 57385
const INNER = 57386
const OUTER = 57387
const CROSS = 57388
const NATURAL = 57389
const USE = 57390
const FORCE = 57391
const ON = 57392
const OR = 57393
const AND = 57394
const NOT = 57395
const BETWEEN = 57396
const CASE = 57397
const WHEN = 57398
const THEN = 57399
const ELSE = 57400
const LE = 57401
const GE = 57402
const NE = 57403
const NULL_SAFE_EQUAL = 57404
const IS = 57405
const LIKE = 57406
const IN = 57407
const UNARY = 57408
const END = 57409
const BEGIN = 57410
const START = 57411
const TRANSACTION = 57412
const COMMIT = 57413
const ROLLBACK = 57414
const NAMES = 57415
const REPLACE = 57416
const ADMIN = 57417
const HELP = 57418
const OFFSET = 57419
const COLLATE = 57420
const CREATE = 57421
const ALTER = 57422
const DROP = 57423
const RENAME = 57424
const TABLE = 57425
const INDEX = 57426
const VIEW = 57427
const TO = 57428
const IGNORE = 57429
const IF = 57430
const UNIQUE = 57431
const USING = 57432
const TRUNCATE = 57433

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"SELECT",
	"INSERT",
	"UPDATE",
	"DELETE",
	"FROM",
	"WHERE",
	"GROUP",
	"HAVING",
	"ORDER",
	"BY",
	"LIMIT",
	"FOR",
	"ALL",
	"DISTINCT",
	"AS",
	"EXISTS",
	"NULL",
	"ASC",
	"DESC",
	"VALUES",
	"INTO",
	"DUPLICATE",
	"KEY",
	"DEFAULT",
	"SET",
	"LOCK",
	"ID",
	"STRING",
	"NUMBER",
	"VALUE_ARG",
	"COMMENT",
	"'('",
	"'~'",
	"UNION",
	"MINUS",
	"EXCEPT",
	"INTERSECT",
	"','",
	"JOIN",
	"STRAIGHT_JOIN",
	"LEFT",
	"RIGHT",
	"INNER",
	"OUTER",
	"CROSS",
	"NATURAL",
	"USE",
	"FORCE",
	"ON",
	"OR",
	"AND",
	"NOT",
	"BETWEEN",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"'='",
	"'<'",
	"'>'",
	"LE",
	"GE",
	"NE",
	"NULL_SAFE_EQUAL",
	"IS",
	"LIKE",
	"IN",
	"'|'",
	"'&'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'^'",
	"'.'",
	"UNARY",
	"END",
	"BEGIN",
	"START",
	"TRANSACTION",
	"COMMIT",
	"ROLLBACK",
	"NAMES",
	"REPLACE",
	"ADMIN",
	"HELP",
	"OFFSET",
	"COLLATE",
	"CREATE",
	"ALTER",
	"DROP",
	"RENAME",
	"TABLE",
	"INDEX",
	"VIEW",
	"TO",
	"IGNORE",
	"IF",
	"UNIQUE",
	"USING",
	"TRUNCATE",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 647

var yyAct = [...]int16{
	111, 108, 315, 352, 187, 385, 102, 139, 74, 346,
	270, 120, 394, 185, 229, 188, 3, 148, 97, 265,
	199, 98, 60, 92, 76, 394, 109, 118, 211, 88,
	125, 81, 53, 279, 119, 63, 142, 79, 115, 116,
	117, 394, 133, 123, 162, 161, 156, 78, 77, 47,
	83, 49, 66, 85, 156, 50, 156, 89, 258, 205,
	227, 363, 114, 118, 126, 362, 125, 72, 361, 96,
	119, 334, 336, 79, 115, 116, 117, 396, 106, 123,
	121, 122, 103, 138, 37, 38, 39, 40, 82, 132,
	395, 146, 84, 141, 78, 152, 130, 256, 105, 54,
	126, 158, 52, 62, 53, 79, 393, 58, 150, 124,
	343, 342, 184, 186, 147, 298, 121, 122, 154, 307,
	189, 305, 335, 257, 190, 226, 193, 55, 56, 57,
	78, 77, 78, 77, 274, 160, 206, 135, 198, 94,
	196, 171, 399, 134, 208, 124, 266, 203, 204, 207,
	137, 197, 243, 259, 221, 161, 201, 246, 162, 161,
	235, 206, 75, 61, 345, 242, 241, 233, 237, 238,
	103, 222, 174, 175, 176, 171, 225, 239, 234, 87,
	244, 245, 131, 248, 249, 250, 251, 252, 253, 254,
	255, 240, 247, 347, 236, 287, 288, 289, 290, 291,
	358, 292, 293, 162, 161, 103, 103, 272, 217, 347,
	261, 263, 276, 266, 275, 310, 273, 145, 360, 269,
	277, 267, 328, 215, 78, 77, 218, 329, 78, 283,
	326, 359, 281, 332, 51, 327, 331, 90, 150, 330,
	280, 131, 200, 233, 258, 369, 297, 200, 262, 284,
	114, 118, 282, 379, 125, 232, 300, 301, 119, 338,
	231, 101, 115, 116, 117, 378, 106, 123, 299, 78,
	77, 377, 304, 311, 285, 318, 103, 313, 71, 131,
	314, 306, 268, 150, 309, 312, 105, 155, 126, 93,
	214, 216, 213, 37, 38, 39, 40, 233, 233, 133,
	324, 325, 194, 19, 121, 122, 99, 192, 191, 321,
	172, 173, 174, 175, 176, 171, 341, 349, 223, 93,
	156, 127, 64, 348, 344, 93, 296, 354, 79, 232,
	350, 353, 159, 124, 231, 339, 337, 260, 295, 320,
	19, 20, 21, 22, 64, 319, 170, 169, 172, 173,
	174, 175, 176, 171, 364, 371, 372, 220, 391, 365,
	219, 207, 375, 374, 23, 376, 373, 202, 62, 153,
	143, 203, 392, 383, 140, 136, 384, 86, 386, 386,
	386, 381, 382, 353, 387, 388, 34, 129, 380, 366,
	78, 77, 128, 91, 19, 400, 303, 209, 397, 144,
	401, 69, 402, 67, 357, 170, 169, 172, 173, 174,
	175, 176, 171, 149, 316, 317, 271, 356, 28, 29,
	323, 30, 31, 367, 32, 33, 200, 73, 398, 24,
	25, 27, 26, 389, 114, 118, 19, 42, 125, 18,
	17, 35, 119, 16, 15, 101, 115, 116, 117, 14,
	106, 123, 19, 170, 169, 172, 173, 174, 175, 176,
	171, 13, 12, 95, 210, 48, 278, 114, 118, 212,
	105, 125, 126, 368, 340, 119, 80, 151, 79, 115,
	116, 117, 390, 106, 123, 370, 351, 355, 121, 122,
	99, 170, 169, 172, 173, 174, 175, 176, 171, 322,
	19, 308, 195, 105, 264, 126, 170, 169, 172, 173,
	174, 175, 176, 171, 113, 110, 118, 124, 112, 125,
	224, 121, 122, 119, 107, 163, 79, 115, 116, 117,
	118, 133, 123, 125, 104, 333, 230, 119, 302, 286,
	79, 115, 116, 117, 228, 133, 123, 100, 294, 157,
	124, 68, 36, 126, 70, 170, 169, 172, 173, 174,
	175, 176, 171, 11, 10, 9, 8, 126, 7, 121,
	122, 169, 172, 173, 174, 175, 176, 171, 6, 5,
	4, 2, 1, 121, 122, 287, 288, 289, 290, 291,
	0, 292, 293, 0, 0, 0, 0, 0, 124, 0,
	0, 0, 0, 0, 0, 0, 0, 165, 167, 0,
	41, 0, 124, 177, 178, 179, 180, 181, 182, 183,
	168, 166, 164, 170, 169, 172, 173, 174, 175, 176,
	171, 43, 44, 45, 46, 0, 0, 0, 0, 0,
	0, 0, 0, 59, 0, 0, 65,
}

var yyPact = [...]int16{
	335, -1000, -1000, 255, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -49, 2, 1, 29, -1000, 22,
	-1000, -1000, -1000, 72, 291, -1000, 431, 386, -1000, -1000,
	-1000, 383, -1000, -70, 337, 418, 74, -72, -11, 291,
	-1000, -6, 291, -1000, 346, -74, 291, -74, -1000, 368,
	283, -1000, 59, -1000, -1000, -29, -1000, -1000, 414, -1000,
	286, 367, 358, 337, 199, 509, -1000, 81, -1000, 57,
	344, 94, 291, -1000, 343, -1000, -65, 339, 379, 164,
	291, 337, 389, 297, 338, 337, -1000, 278, -1000, -1000,
	313, 55, 149, 551, -1000, 42, 447, -1000, -1000, -1000,
	509, 272, 271, -1000, 266, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 509, -1000, 337, 297,
	416, 297, 274, 495, 6, 330, -1000, 377, -77, -1000,
	195, -1000, 329, -1000, -1000, 326, -1000, 289, -1000, 263,
	255, 18, -1000, -1000, -1000, 224, 414, -1000, -1000, 291,
	118, 42, 42, 509, 263, 95, 509, 509, 136, 509,
	509, 509, 509, 509, 509, 509, 509, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 551, -10, 16, 46, 551,
	-1000, 230, 414, -1000, 431, 87, 434, 253, 237, 403,
	42, -1000, 509, 434, 434, -1000, -1000, 54, -1000, -1000,
	161, 291, -1000, -68, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 389, 297, 210, -1000, -1000, 297, 232, 542,
	307, 298, 35, -1000, -1000, -1000, -1000, -1000, 100, 434,
	-1000, 263, 509, 509, 434, 483, -1000, 375, 236, 498,
	-1000, 96, 96, 62, 62, 62, -1000, -1000, 509, -1000,
	-1000, 14, 414, 12, 154, -1000, 42, 389, 297, 403,
	399, 401, 149, 434, 291, 314, -1000, -1000, 308, -1000,
	-1000, 199, 263, -1000, 409, 224, 224, -1000, -1000, 187,
	179, 196, 193, 190, 20, -1000, 305, 152, 304, -1000,
	434, 419, 509, -1000, 434, -1000, 4, -1000, 28, -1000,
	509, 104, 156, 140, 399, -1000, 509, 509, -1000, -1000,
	-1000, -1000, 405, 390, 542, 147, -1000, 188, -1000, 175,
	-1000, -1000, -1000, -1000, -31, -34, -38, -1000, -1000, -1000,
	509, 434, -1000, -1000, 434, 509, -1000, 363, -1000, -1000,
	381, 203, -1000, 333, -1000, 403, 42, 509, 42, -1000,
	-1000, 235, 229, 217, 434, 434, 361, 509, 509, 509,
	-1000, -1000, -1000, 399, 149, 202, 149, 291, 291, 291,
	426, 434, 434, -1000, 342, -1, -1000, -17, -30, 297,
	-1000, 421, 71, -1000, 291, -1000, -1000, 199, -1000, 291,
	-1000, 291, -1000,
}

var yyPgo = [...]int16{
	0, 582, 581, 15, 580, 579, 578, 568, 566, 565,
	564, 563, 610, 554, 552, 551, 234, 18, 21, 549,
	548, 547, 544, 14, 539, 536, 22, 535, 5, 20,
	6, 534, 525, 17, 524, 13, 26, 4, 520, 518,
	11, 515, 1, 514, 504, 19, 502, 501, 499, 487,
	10, 486, 3, 485, 2, 482, 23, 477, 9, 8,
	24, 179, 476, 469, 466, 465, 464, 0, 7, 463,
	462, 461, 449, 444, 443, 440, 439, 437,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
	3, 4, 4, 73, 73, 5, 6, 7, 7, 7,
	70, 70, 71, 72, 74, 74, 75, 76, 8, 8,
	8, 9, 9, 9, 10, 11, 11, 11, 77, 12,
	13, 13, 14, 14, 14, 14, 14, 15, 15, 17,
	17, 18, 18, 18, 21, 21, 19, 19, 19, 22,
	22, 23, 23, 23, 23, 20, 20, 20, 24, 24,
	24, 24, 24, 24, 24, 24, 24, 25, 25, 25,
	26, 26, 27, 27, 27, 27, 28, 28, 29, 29,
	30, 30, 30, 30, 30, 31, 31, 31, 31, 31,
	31, 31, 31, 31, 31, 32, 32, 32, 32, 32,
	32, 32, 33, 33, 38, 38, 36, 36, 40, 37,
	37, 35, 35, 35, 35, 35, 35, 35, 35, 35,
	35, 35, 35, 35, 35, 35, 35, 35, 39, 39,
	41, 41, 41, 43, 46, 46, 44, 44, 45, 47,
	47, 42, 42, 42, 34, 34, 34, 34, 34, 48,
	48, 49, 49, 50, 50, 51, 51, 52, 53, 53,
	53, 54, 54, 54, 54, 55, 55, 55, 56, 56,
	57, 57, 58, 58, 59, 59, 60, 60, 61, 61,
	62, 62, 16, 16, 63, 63, 63, 63, 63, 64,
	64, 65, 65, 66, 66, 67, 68, 69, 69,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 4, 12,
	3, 8, 8, 6, 6, 8, 7, 3, 4, 6,
	1, 2, 1, 1, 4, 2, 2, 4, 5, 8,
	4, 6, 7, 4, 5, 4, 5, 5, 0, 2,
	0, 2, 1, 2, 1, 1, 1, 0, 1, 1,
	3, 1, 2, 3, 1, 1, 0, 1, 2, 1,
	3, 3, 3, 3, 5, 0, 1, 2, 1, 1,
	2, 3, 2, 3, 2, 2, 2, 1, 3, 1,
	1, 3, 0, 5, 5, 5, 1, 3, 0, 2,
	1, 3, 3, 2, 3, 3, 3, 4, 3, 4,
	5, 6, 3, 4, 2, 1, 1, 1, 1, 1,
	1, 1, 2, 1, 1, 3, 3, 1, 3, 1,
	3, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 3, 4, 5, 4, 1, 1, 1,
	1, 1, 1, 5, 0, 1, 1, 2, 4, 0,
	2, 1, 3, 5, 1, 1, 1, 1, 1, 0,
	3, 0, 2, 0, 3, 1, 3, 2, 0, 1,
	1, 0, 2, 4, 4, 0, 2, 4, 0, 3,
	1, 3, 0, 5, 1, 3, 3, 3, 0, 2,
	0, 3, 0, 1, 1, 1, 1, 1, 1, 0,
	1, 0, 1, 0, 2, 1, 0, 0, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, -7, -8, -9,
	-10, -11, -70, -71, -72, -73, -74, -75, -76, 5,
	6, 7, 8, 29, 94, 95, 97, 96, 83, 84,
	86, 87, 89, 90, 51, 106, -14, 38, 39, 40,
	41, -12, -77, -12, -12, -12, -12, 98, -65, 100,
	104, -16, 100, 102, 98, 98, 99, 100, 85, -12,
	-26, 91, 31, -67, 31, -12, -3, 17, -15, 18,
	-13, -16, -26, 9, -59, 88, -60, -42, -67, 31,
	-62, 103, 99, -67, 98, -67, 31, -61, 103, -67,
	-61, 25, -56, 36, 80, -69, 98, -17, -18, 76,
	-21, 31, -30, -35, -31, 56, 36, -34, -42, -36,
	-41, -67, -39, -43, 20, 32, 33, 34, 21, 28,
	-40, 74, 75, 37, 103, 24, 58, 35, 25, 29,
	-26, 42, -35, 36, 62, 80, 31, 56, -67, -68,
	31, -68, 101, 31, 20, 53, -67, -26, -33, 24,
	-3, -57, -42, 31, -26, 9, 42, -19, -67, 19,
	80, 55, 54, -32, 71, 56, 70, 57, 69, 73,
	72, 79, 74, 75, 76, 77, 78, 62, 63, 64,
	65, 66, 67, 68, -30, -35, -30, -37, -3, -35,
	-35, 36, 36, -40, 36, -46, -35, -26, -59, -29,
	10, -60, 93, -35, -35, 53, -67, 31, -68, 20,
	-66, 105, -63, 97, 95, 28, 96, 13, 31, 31,
	31, -68, -56, 29, -38, -36, 107, 42, -22, -23,
	-25, 36, 31, -40, -18, -67, 76, -30, -30, -35,
	-36, 71, 70, 57, -35, -35, 21, 56, -35, -35,
	-35, -35, -35, -35, -35, -35, 107, 107, 42, 107,
	107, -17, 18, -17, -44, -45, 59, -56, 29, -29,
	-50, 13, -30, -35, 80, 53, -67, -68, -64, 101,
	-33, -59, 42, -42, -29, 42, -24, 43, 44, 45,
	46, 47, 49, 50, -20, 31, 19, -23, 80, -36,
	-35, -35, 55, 21, -35, 107, -17, 107, -47, -45,
	61, -30, -33, -59, -50, -54, 15, 14, -67, 31,
	31, -36, -48, 11, -23, -23, 43, 48, 43, 48,
	43, 43, 43, -27, 51, 102, 52, 31, 107, 31,
	55, -35, 107, 82, -35, 60, -58, 53, -58, -54,
	-35, -51, -52, -35, -68, -49, 12, 14, 53, 43,
	43, 99, 99, 99, -35, -35, 26, 42, 92, 42,
	-53, 22, 23, -50, -30, -37, -30, 36, 36, 36,
	27, -35, -35, -52, -54, -28, -67, -28, -28, 7,
	-55, 16, 30, 107, 42, 107, 107, -59, 7, 71,
	-67, -67, -67,
}

var yyDef = [...]int16{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 11, 12, 13, 14, 15, 16, 17, 48,
	48, 48, 48, 48, 211, 202, 0, 0, 30, 0,
	32, 33, 48, 0, 0, 48, 0, 52, 54, 55,
	56, 57, 50, 202, 0, 0, 0, 200, 0, 0,
	212, 0, 0, 203, 0, 198, 0, 198, 31, 0,
	188, 35, 90, 36, 215, 217, 20, 53, 0, 58,
	49, 0, 0, 0, 27, 0, 194, 0, 161, 215,
	0, 0, 0, 216, 0, 216, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 218, 18, 59, 61,
	66, 215, 64, 65, 100, 0, 0, 131, 132, 133,
	0, 161, 0, 147, 0, 164, 165, 166, 167, 168,
	127, 150, 151, 152, 148, 149, 154, 51, 0, 0,
	98, 0, 28, 0, 0, 0, 216, 0, 213, 40,
	0, 43, 0, 45, 199, 0, 216, 188, 34, 0,
	123, 0, 190, 91, 37, 0, 0, 62, 67, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 115, 116, 117,
	118, 119, 120, 121, 103, 0, 0, 0, 0, 129,
	142, 0, 0, 114, 0, 0, 155, 188, 98, 173,
	0, 195, 0, 129, 196, 197, 162, 215, 38, 201,
	0, 0, 216, 209, 204, 205, 206, 207, 208, 44,
	46, 47, 0, 0, 122, 124, 189, 0, 98, 69,
	75, 0, 87, 89, 60, 68, 63, 101, 102, 105,
	106, 0, 0, 0, 108, 0, 112, 0, 134, 135,
	136, 137, 138, 139, 140, 141, 104, 126, 0, 128,
	143, 0, 0, 0, 159, 156, 0, 0, 0, 173,
	181, 0, 99, 29, 0, 0, 214, 41, 0, 210,
	23, 24, 0, 191, 169, 0, 0, 78, 79, 0,
	0, 0, 0, 0, 92, 76, 0, 0, 0, 107,
	109, 0, 0, 113, 130, 144, 0, 146, 0, 157,
	0, 0, 192, 192, 181, 26, 0, 0, 163, 216,
	42, 125, 171, 0, 70, 73, 80, 0, 82, 0,
	84, 85, 86, 71, 0, 0, 0, 77, 72, 88,
	0, 110, 145, 153, 160, 0, 21, 0, 22, 25,
	182, 174, 175, 178, 39, 173, 0, 0, 0, 81,
	83, 0, 0, 0, 111, 158, 0, 0, 0, 0,
	177, 179, 180, 181, 172, 170, 74, 0, 0, 0,
	0, 183, 184, 176, 185, 0, 96, 0, 0, 0,
	19, 0, 0, 93, 0, 94, 95, 193, 186, 0,
	97, 0, 187,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 78, 73, 3,
	36, 107, 76, 74, 42, 75, 80, 77, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	63, 62, 64, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 79, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 72, 3, 37,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 38, 39, 40, 41, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 65, 66, 67,
	68, 69, 70, 71, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 101, 102, 103, 104, 105, 106,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:193
		{
			SetParseTree(yylex, yyDollar[1].statement)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:199
		{
			yyVAL.statement = yyDollar[1].selStmt
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:220
		{
			yyVAL.selStmt = &SimpleSelect{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs}
		}
	case 19:
		yyDollar = yyS[yypt-12 : yypt+1]
//line ./sqlparser/sql.y:224
		{
			yyVAL.selStmt = &Select{Comments: Comments(yyDollar[2].bytes2), Distinct: yyDollar[3].str, SelectExprs: yyDollar[4].selectExprs, From: yyDollar[6].tableExprs, Where: NewWhere(AST_WHERE, yyDollar[7].boolExpr), GroupBy: GroupBy(yyDollar[8].valExprs), Having: NewWhere(AST_HAVING, yyDollar[9].boolExpr), OrderBy: yyDollar[10].orderBy, Limit: yyDollar[11].limit, Lock: yyDollar[12].str}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:228
		{
			yyVAL.selStmt = &Union{Type: yyDollar[2].str, Left: yyDollar[1].selStmt, Right: yyDollar[3].selStmt}
		}
	case 21:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ./sqlparser/sql.y:235
		{
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Ignore: yyDollar[3].str, Table: yyDollar[5].tableName, Columns: yyDollar[6].columns, Rows: yyDollar[7].insRows, OnDup: OnDup(yyDollar[8].updateExprs)}
		}
	case 22:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ./sqlparser/sql.y:239
		{
			cols := make(Columns, 0, len(yyDollar[7].updateExprs))
			vals := make(ValTuple, 0, len(yyDollar[7].updateExprs))
			for _, col := range yyDollar[7].updateExprs {
				cols = append(cols, &NonStarExpr{Expr: col.Name})
				vals = append(vals, col.Expr)
			}
			yyVAL.statement = &Insert{Comments: Comments(yyDollar[2].bytes2), Ignore: yyDollar[3].str, Table: yyDollar[5].tableName, Columns: cols, Rows: Values{vals}, OnDup: OnDup(yyDollar[8].updateExprs)}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./sqlparser/sql.y:251
		{
			yyVAL.statement = &Replace{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: yyDollar[5].columns, Rows: yyDollar[6].insRows}
		}
	case 24:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./sqlparser/sql.y:255
		{
			cols := make(Columns, 0, len(yyDollar[6].updateExprs))
			vals := make(ValTuple, 0, len(yyDollar[6].updateExprs))
			for _, col := range yyDollar[6].updateExprs {
				cols = append(cols, &NonStarExpr{Expr: col.Name})
				vals = append(vals, col.Expr)
			}
			yyVAL.statement = &Replace{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Columns: cols, Rows: Values{vals}}
		}
	case 25:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ./sqlparser/sql.y:268
		{
			yyVAL.statement = &Update{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[3].tableName, Exprs: yyDollar[5].updateExprs, Where: NewWhere(AST_WHERE, yyDollar[6].boolExpr), OrderBy: yyDollar[7].orderBy, Limit: yyDollar[8].limit}
		}
	case 26:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ./sqlparser/sql.y:274
		{
			yyVAL.statement = &Delete{Comments: Comments(yyDollar[2].bytes2), Table: yyDollar[4].tableName, Where: NewWhere(AST_WHERE, yyDollar[5].boolExpr), OrderBy: yyDollar[6].orderBy, Limit: yyDollar[7].limit}
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:280
		{
			yyVAL.statement = &Set{Comments: Comments(yyDollar[2].bytes2), Exprs: yyDollar[3].updateExprs}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:284
		{
			yyVAL.statement = &Set{Comments: Comments(yyDollar[2].bytes2), Exprs: UpdateExprs{&UpdateExpr{Name: &ColName{Name: []byte("names")}, Expr: yyDollar[4].valExpr}}}
		}
	case 29:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./sqlparser/sql.y:288
		{
			yyVAL.statement = &Set{
				Comments: Comments(yyDollar[2].bytes2),
				Exprs: UpdateExprs{
					&UpdateExpr{
						Name: &ColName{Name: []byte("names")}, Expr: yyDollar[4].valExpr,
					},
					&UpdateExpr{
						Name: &ColName{Name: []byte("collate")}, Expr: yyDollar[6].valExpr,
					},
				},
			}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:304
		{
			yyVAL.statement = &Begin{}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:308
		{
			yyVAL.statement = &Begin{}
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:315
		{
			yyVAL.statement = &Commit{}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:321
		{
			yyVAL.statement = &Rollback{}
		}
	case 34:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:327
		{
			yyVAL.statement = &Admin{Region: yyDollar[2].tableName, Columns: yyDollar[3].columns, Rows: yyDollar[4].insRows}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:331
		{
			yyVAL.statement = &AdminHelp{}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:337
		{
			yyVAL.statement = &UseDB{DB: string(yyDollar[2].bytes)}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:343
		{
			yyVAL.statement = &Truncate{Comments: Comments(yyDollar[2].bytes2), TableOpt: yyDollar[3].str, Table: yyDollar[4].tableName}
		}
	case 38:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:349
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[4].bytes}
		}
	case 39:
		yyDollar = yyS[yypt-8 : yypt+1]
//line ./sqlparser/sql.y:353
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[7].bytes, NewName: yyDollar[7].bytes}
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:358
		{
			yyVAL.statement = &DDL{Action: AST_CREATE, NewName: yyDollar[3].bytes}
		}
	case 41:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./sqlparser/sql.y:364
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Ignore: yyDollar[2].str, Table: yyDollar[4].bytes, NewName: yyDollar[4].bytes}
		}
	case 42:
		yyDollar = yyS[yypt-7 : yypt+1]
//line ./sqlparser/sql.y:368
		{
			// Change this to a rename statement
			yyVAL.statement = &DDL{Action: AST_RENAME, Ignore: yyDollar[2].str, Table: yyDollar[4].bytes, NewName: yyDollar[7].bytes}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:373
		{
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[3].bytes, NewName: yyDollar[3].bytes}
		}
	case 44:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:379
		{
			yyVAL.statement = &DDL{Action: AST_RENAME, Table: yyDollar[3].bytes, NewName: yyDollar[5].bytes}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:385
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 46:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:389
		{
			// Change this to an alter statement
			yyVAL.statement = &DDL{Action: AST_ALTER, Table: yyDollar[5].bytes, NewName: yyDollar[5].bytes}
		}
	case 47:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:394
		{
			yyVAL.statement = &DDL{Action: AST_DROP, Table: yyDollar[4].bytes}
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:399
		{
			SetAllowComments(yylex, true)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:403
		{
			yyVAL.bytes2 = yyDollar[2].bytes2
			SetAllowComments(yylex, false)
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:409
		{
			yyVAL.bytes2 = nil
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:413
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[2].bytes)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:419
		{
			yyVAL.str = AST_UNION
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:423
		{
			yyVAL.str = AST_UNION_ALL
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:427
		{
			yyVAL.str = AST_SET_MINUS
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:431
		{
			yyVAL.str = AST_EXCEPT
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:435
		{
			yyVAL.str = AST_INTERSECT
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:440
		{
			yyVAL.str = ""
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:444
		{
			yyVAL.str = AST_DISTINCT
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:450
		{
			yyVAL.selectExprs = SelectExprs{yyDollar[1].selectExpr}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:454
		{
			yyVAL.selectExprs = append(yyVAL.selectExprs, yyDollar[3].selectExpr)
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:460
		{
			yyVAL.selectExpr = &StarExpr{}
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:464
		{
			yyVAL.selectExpr = &NonStarExpr{Expr: yyDollar[1].expr, As: yyDollar[2].bytes}
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:468
		{
			yyVAL.selectExpr = &StarExpr{TableName: yyDollar[1].bytes}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:474
		{
			yyVAL.expr = yyDollar[1].boolExpr
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:478
		{
			yyVAL.expr = yyDollar[1].valExpr
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:483
		{
			yyVAL.bytes = nil
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:487
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:491
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:497
		{
			yyVAL.tableExprs = TableExprs{yyDollar[1].tableExpr}
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:501
		{
			yyVAL.tableExprs = append(yyVAL.tableExprs, yyDollar[3].tableExpr)
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:507
		{
			yyVAL.tableExpr = &AliasedTableExpr{Expr: yyDollar[1].smTableExpr, As: yyDollar[2].bytes, Hints: yyDollar[3].indexHints}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:511
		{
			yyVAL.tableExpr = &ParenTableExpr{Expr: yyDollar[2].tableExpr}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:515
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr}
		}
	case 74:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:519
		{
			yyVAL.tableExpr = &JoinTableExpr{LeftExpr: yyDollar[1].tableExpr, Join: yyDollar[2].str, RightExpr: yyDollar[3].tableExpr, On: yyDollar[5].boolExpr}
		}
	case 75:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:524
		{
			yyVAL.bytes = nil
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:528
		{
			yyVAL.bytes = yyDollar[1].bytes
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:532
		{
			yyVAL.bytes = yyDollar[2].bytes
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:538
		{
			yyVAL.str = AST_JOIN
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:542
		{
			yyVAL.str = AST_STRAIGHT_JOIN
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:546
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:550
		{
			yyVAL.str = AST_LEFT_JOIN
		}
	case 82:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:554
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:558
		{
			yyVAL.str = AST_RIGHT_JOIN
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:562
		{
			yyVAL.str = AST_JOIN
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:566
		{
			yyVAL.str = AST_CROSS_JOIN
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:570
		{
			yyVAL.str = AST_NATURAL_JOIN
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:576
		{
			yyVAL.smTableExpr = &TableName{Name: yyDollar[1].bytes}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:580
		{
			yyVAL.smTableExpr = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:584
		{
			yyVAL.smTableExpr = yyDollar[1].subquery
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:590
		{
			yyVAL.tableName = &TableName{Name: yyDollar[1].bytes}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:594
		{
			yyVAL.tableName = &TableName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:599
		{
			yyVAL.indexHints = nil
		}
	case 93:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:603
		{
			yyVAL.indexHints = &IndexHints{Type: AST_USE, Indexes: yyDollar[4].bytes2}
		}
	case 94:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:607
		{
			yyVAL.indexHints = &IndexHints{Type: AST_IGNORE, Indexes: yyDollar[4].bytes2}
		}
	case 95:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:611
		{
			yyVAL.indexHints = &IndexHints{Type: AST_FORCE, Indexes: yyDollar[4].bytes2}
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:617
		{
			yyVAL.bytes2 = [][]byte{yyDollar[1].bytes}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:621
		{
			yyVAL.bytes2 = append(yyDollar[1].bytes2, yyDollar[3].bytes)
		}
	case 98:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:626
		{
			yyVAL.boolExpr = nil
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:630
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:637
		{
			yyVAL.boolExpr = &AndExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 102:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:641
		{
			yyVAL.boolExpr = &OrExpr{Left: yyDollar[1].boolExpr, Right: yyDollar[3].boolExpr}
		}
	case 103:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:645
		{
			yyVAL.boolExpr = &NotExpr{Expr: yyDollar[2].boolExpr}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:649
		{
			yyVAL.boolExpr = &ParenBoolExpr{Expr: yyDollar[2].boolExpr}
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:655
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: yyDollar[2].str, Right: yyDollar[3].valExpr}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:659
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_IN, Right: yyDollar[3].tuple}
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:663
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_IN, Right: yyDollar[4].tuple}
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:667
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_LIKE, Right: yyDollar[3].valExpr}
		}
	case 109:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:671
		{
			yyVAL.boolExpr = &ComparisonExpr{Left: yyDollar[1].valExpr, Operator: AST_NOT_LIKE, Right: yyDollar[4].valExpr}
		}
	case 110:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:675
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_BETWEEN, From: yyDollar[3].valExpr, To: yyDollar[5].valExpr}
		}
	case 111:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./sqlparser/sql.y:679
		{
			yyVAL.boolExpr = &RangeCond{Left: yyDollar[1].valExpr, Operator: AST_NOT_BETWEEN, From: yyDollar[4].valExpr, To: yyDollar[6].valExpr}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:683
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NULL, Expr: yyDollar[1].valExpr}
		}
	case 113:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:687
		{
			yyVAL.boolExpr = &NullCheck{Operator: AST_IS_NOT_NULL, Expr: yyDollar[1].valExpr}
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:691
		{
			yyVAL.boolExpr = &ExistsExpr{Subquery: yyDollar[2].subquery}
		}
	case 115:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:697
		{
			yyVAL.str = AST_EQ
		}
	case 116:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:701
		{
			yyVAL.str = AST_LT
		}
	case 117:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:705
		{
			yyVAL.str = AST_GT
		}
	case 118:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:709
		{
			yyVAL.str = AST_LE
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:713
		{
			yyVAL.str = AST_GE
		}
	case 120:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:717
		{
			yyVAL.str = AST_NE
		}
	case 121:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:721
		{
			yyVAL.str = AST_NSE
		}
	case 122:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:727
		{
			yyVAL.insRows = yyDollar[2].values
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:731
		{
			yyVAL.insRows = yyDollar[1].selStmt
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:737
		{
			yyVAL.values = Values{yyDollar[1].tuple}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:741
		{
			yyVAL.values = append(yyDollar[1].values, yyDollar[3].tuple)
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:747
		{
			yyVAL.tuple = ValTuple(yyDollar[2].valExprs)
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:751
		{
			yyVAL.tuple = yyDollar[1].subquery
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:757
		{
			yyVAL.subquery = &Subquery{yyDollar[2].selStmt}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:763
		{
			yyVAL.valExprs = ValExprs{yyDollar[1].valExpr}
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:767
		{
			yyVAL.valExprs = append(yyDollar[1].valExprs, yyDollar[3].valExpr)
		}
	case 131:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:773
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 132:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:777
		{
			yyVAL.valExpr = yyDollar[1].colName
		}
	case 133:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:781
		{
			yyVAL.valExpr = yyDollar[1].tuple
		}
	case 134:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:785
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITAND, Right: yyDollar[3].valExpr}
		}
	case 135:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:789
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITOR, Right: yyDollar[3].valExpr}
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:793
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_BITXOR, Right: yyDollar[3].valExpr}
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:797
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_PLUS, Right: yyDollar[3].valExpr}
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:801
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MINUS, Right: yyDollar[3].valExpr}
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:805
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MULT, Right: yyDollar[3].valExpr}
		}
	case 140:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:809
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_DIV, Right: yyDollar[3].valExpr}
		}
	case 141:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:813
		{
			yyVAL.valExpr = &BinaryExpr{Left: yyDollar[1].valExpr, Operator: AST_MOD, Right: yyDollar[3].valExpr}
		}
	case 142:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:817
		{
			if num, ok := yyDollar[2].valExpr.(NumVal); ok {
				switch yyDollar[1].byt {
				case '-':
					yyVAL.valExpr = append(NumVal("-"), num...)
				case '+':
					yyVAL.valExpr = num
				default:
					yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
				}
			} else {
				yyVAL.valExpr = &UnaryExpr{Operator: yyDollar[1].byt, Expr: yyDollar[2].valExpr}
			}
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:832
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes}
		}
	case 144:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:836
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 145:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:840
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Distinct: true, Exprs: yyDollar[4].selectExprs}
		}
	case 146:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:844
		{
			yyVAL.valExpr = &FuncExpr{Name: yyDollar[1].bytes, Exprs: yyDollar[3].selectExprs}
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:848
		{
			yyVAL.valExpr = yyDollar[1].caseExpr
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:854
		{
			yyVAL.bytes = IF_BYTES
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:858
		{
			yyVAL.bytes = VALUES_BYTES
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:864
		{
			yyVAL.byt = AST_UPLUS
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:868
		{
			yyVAL.byt = AST_UMINUS
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:872
		{
			yyVAL.byt = AST_TILDA
		}
	case 153:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:878
		{
			yyVAL.caseExpr = &CaseExpr{Expr: yyDollar[2].valExpr, Whens: yyDollar[3].whens, Else: yyDollar[4].valExpr}
		}
	case 154:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:883
		{
			yyVAL.valExpr = nil
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:887
		{
			yyVAL.valExpr = yyDollar[1].valExpr
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:893
		{
			yyVAL.whens = []*When{yyDollar[1].when}
		}
	case 157:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:897
		{
			yyVAL.whens = append(yyDollar[1].whens, yyDollar[2].when)
		}
	case 158:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:903
		{
			yyVAL.when = &When{Cond: yyDollar[2].boolExpr, Val: yyDollar[4].valExpr}
		}
	case 159:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:908
		{
			yyVAL.valExpr = nil
		}
	case 160:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:912
		{
			yyVAL.valExpr = yyDollar[2].valExpr
		}
	case 161:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:918
		{
			yyVAL.colName = &ColName{Name: yyDollar[1].bytes}
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:922
		{
			yyVAL.colName = &ColName{Qualifier: yyDollar[1].bytes, Name: yyDollar[3].bytes}
		}
	case 163:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:926
		{
			yyVAL.colName = &ColName{Qualifier: yyDollar[3].bytes, Name: yyDollar[5].bytes}
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:932
		{
			yyVAL.valExpr = StrVal(yyDollar[1].bytes)
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:936
		{
			yyVAL.valExpr = NumVal(yyDollar[1].bytes)
		}
	case 166:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:940
		{
			yyVAL.valExpr = ValArg(yyDollar[1].bytes)
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:944
		{
			yyVAL.valExpr = &NullVal{}
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:948
		{
			yyVAL.valExpr = &DefaultVal{}
		}
	case 169:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:953
		{
			yyVAL.valExprs = nil
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:957
		{
			yyVAL.valExprs = yyDollar[3].valExprs
		}
	case 171:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:962
		{
			yyVAL.boolExpr = nil
		}
	case 172:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:966
		{
			yyVAL.boolExpr = yyDollar[2].boolExpr
		}
	case 173:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:971
		{
			yyVAL.orderBy = nil
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:975
		{
			yyVAL.orderBy = yyDollar[3].orderBy
		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:981
		{
			yyVAL.orderBy = OrderBy{yyDollar[1].order}
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:985
		{
			yyVAL.orderBy = append(yyDollar[1].orderBy, yyDollar[3].order)
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:991
		{
			yyVAL.order = &Order{Expr: yyDollar[1].valExpr, Direction: yyDollar[2].str}
		}
	case 178:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:996
		{
			yyVAL.str = AST_ASC
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1000
		{
			yyVAL.str = AST_ASC
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1004
		{
			yyVAL.str = AST_DESC
		}
	case 181:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1009
		{
			yyVAL.limit = nil
		}
	case 182:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:1013
		{
			yyVAL.limit = &Limit{Rowcount: yyDollar[2].valExpr}
		}
	case 183:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:1017
		{
			yyVAL.limit = &Limit{Offset: yyDollar[2].valExpr, Rowcount: yyDollar[4].valExpr}
		}
	case 184:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:1021
		{
			yyVAL.limit = &Limit{Offset: yyDollar[4].valExpr, Rowcount: yyDollar[2].valExpr}
		}
	case 185:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1026
		{
			yyVAL.str = ""
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:1030
		{
			yyVAL.str = AST_FOR_UPDATE
		}
	case 187:
		yyDollar = yyS[yypt-4 : yypt+1]
//line ./sqlparser/sql.y:1034
		{
			if !bytes.Equal(yyDollar[3].bytes, SHARE) {
				yylex.Error("expecting share")
				return 1
			}
			if !bytes.Equal(yyDollar[4].bytes, MODE) {
				yylex.Error("expecting mode")
				return 1
			}
			yyVAL.str = AST_SHARE_MODE
		}
	case 188:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1047
		{
			yyVAL.columns = nil
		}
	case 189:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1051
		{
			yyVAL.columns = yyDollar[2].columns
		}
	case 190:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1057
		{
			yyVAL.columns = Columns{&NonStarExpr{Expr: yyDollar[1].colName}}
		}
	case 191:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1061
		{
			yyVAL.columns = append(yyVAL.columns, &NonStarExpr{Expr: yyDollar[3].colName})
		}
	case 192:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1066
		{
			yyVAL.updateExprs = nil
		}
	case 193:
		yyDollar = yyS[yypt-5 : yypt+1]
//line ./sqlparser/sql.y:1070
		{
			yyVAL.updateExprs = yyDollar[5].updateExprs
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1076
		{
			yyVAL.updateExprs = UpdateExprs{yyDollar[1].updateExpr}
		}
	case 195:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1080
		{
			yyVAL.updateExprs = append(yyDollar[1].updateExprs, yyDollar[3].updateExpr)
		}
	case 196:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1086
		{
			yyVAL.updateExpr = &UpdateExpr{Name: yyDollar[1].colName, Expr: yyDollar[3].valExpr}
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1090
		{
			yyVAL.updateExpr = &UpdateExpr{Name: yyDollar[1].colName, Expr: StrVal("ON")}
		}
	case 198:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1095
		{
			yyVAL.empty = struct{}{}
		}
	case 199:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:1097
		{
			yyVAL.empty = struct{}{}
		}
	case 200:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1100
		{
			yyVAL.empty = struct{}{}
		}
	case 201:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./sqlparser/sql.y:1102
		{
			yyVAL.empty = struct{}{}
		}
	case 202:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1105
		{
			yyVAL.str = ""
		}
	case 203:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1107
		{
			yyVAL.str = AST_IGNORE
		}
	case 204:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1111
		{
			yyVAL.empty = struct{}{}
		}
	case 205:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1113
		{
			yyVAL.empty = struct{}{}
		}
	case 206:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1115
		{
			yyVAL.empty = struct{}{}
		}
	case 207:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1117
		{
			yyVAL.empty = struct{}{}
		}
	case 208:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1119
		{
			yyVAL.empty = struct{}{}
		}
	case 209:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1122
		{
			yyVAL.empty = struct{}{}
		}
	case 210:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1124
		{
			yyVAL.empty = struct{}{}
		}
	case 211:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1127
		{
			yyVAL.empty = struct{}{}
		}
	case 212:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1129
		{
			yyVAL.empty = struct{}{}
		}
	case 213:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1132
		{
			yyVAL.empty = struct{}{}
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./sqlparser/sql.y:1134
		{
			yyVAL.empty = struct{}{}
		}
	case 215:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1138
		{
			yyVAL.bytes = bytes.ToLower(yyDollar[1].bytes)
		}
	case 216:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1143
		{
			ForceEOF(yylex)
		}
	case 217:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./sqlparser/sql.y:1148
		{
			yyVAL.str = ""
		}
	case 218:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./sqlparser/sql.y:1152
		{
			yyVAL.str = AST_TABLE
		}
	}
	goto yystack /* stack new state and value */
}
